const questions = {
  indonesian: [
    "Apa kenangan favoritmu saat berkencan denganku?",
    "Apa memori seksual favorit kamu tentang kami?",
    "Makanan apa yang mengingatkanmu padaku?",
    "Kapan terakhir kali kamu memikirkan aku secara positif?",
    "Apa hal favorit kamu yang aku lakukan untuk kamu?",
    "Film apa yang mengingatkanmu pada kami?",
    "Di antara orang tua kamu, siapa yang paling kamu sukai?",
    "Manakah dari anak-anak kami yang paling seperti kamu? atau jika kamu belum menjadi orang tua: Apakah kamu pernah membayangkan memiliki anak?",
    "Apa fitur fisik terbaik aku?",
    "Apa yang paling kamu sukai yang aku lakukan di tempat tidur?",
    "Apa waktu favorit kamu untuk menjadi intim?",
    "Apakah kamu lebih suka berciuman atau berpelukan?",
    "Kapan kamu tahu kamu ingin menjadi monogami dengan aku?",
    "Apakah kamu pernah cemburu jika kamu melihat aku berbicara dengan orang lain yang menarik?",
    "Apakah kamu pernah bermimpi tentang aku?",
    "Menurut kamu apa yang paling perlu kita perbaiki dalam hubungan kita?",
    "Jika kamu sakit, apakah kamu pikir aku akan ada untuk merawat kamu?",
    "Apakah kamu percaya bahwa aku mencintaimu?",
    "Kapan kamu tahu kamu ingin menciumku?",
    "Apa aktivitas non-seks favorit kamu yang kita lakukan bersama?",
    "Sebagai seorang anak, apakah kamu mempercayai kedua orang tua kamu?",
    "Apa hal favorit kamu yang pernah aku lakukan untuk acara khusus untuk kamu?",
    "Apa fantasi seksual favorit kamu?",
    "Apa posisi seksual favorit kamu?",
    "Apakah kamu pernah berpikir tentang aku secara seksual di siang hari?",
    "Apa yang bisa aku lakukan untuk membuat kamu lebih mempercayai aku?",
    "Kapan kamu merasa paling dilindungi dan diperhatikan?",
    "Apa yang bisa aku lakukan untuk memastikan kamu merasa aman bersama aku?",
    "Ketika kita hang out dengan teman-teman, apakah aku membuat kamu merasa bahwa kamu masih menjadi prioritas aku?",
    "Saat kita bersama keluargaku, apakah aku membuat kamu merasa seperti kamu masih menjadi prioritas aku?",
    "Apakah kamu memiliki pelanggar kesepakatan, hal-hal yang akan membuat kamu serius mempertimbangkan kembali hubungan kita?",
    "Apa hal pertama yang kamu pikirkan tentang aku?",
    "Kapan kamu pertama kali berpikir aku menarik?",
    "Menurut kamu berapa lama orang harus menunggu sebelum memiliki anak?",
    "Apa yang kamu pelajari tentang pernikahan dari orang tua kamu?",
    "Apa yang kamu pelajari tentang kasih akung fisik dari orang tua kamu?",
    "Apa buku favoritmu?",
    "Apa lagu favoritmu?",
    "Apa film favorit pertama kamu, sebagai seorang anak?",
    "Apa yang ingin kamu lakukan saat pensiun?",
    "Pernahkah kamu membayangkan memiliki cucu?",
    "Apa karir lain yang menurut kamu akan kamu sukai?",
    "Apa fitur fisik favorit kamu sendiri?",
    "Siapa guru favorit kamu ketika kamu masih kecil?",
    "Apa kenangan favoritmu dengan ibumu?",
    "Apa kenangan favoritmu dengan ayahmu?",
    "Siapa orang penting sebelum aku yang memiliki dampak terbesar bagi kamu?",
    "Apa yang kamu pikirkan setelah pengalaman seksual pertama kamu?",
    "Lebih suka SMA atau kuliah?",
    "Ke mana kamu selalu ingin bepergian?",
    "Apakah kamu pernah mempertimbangkan jalur karir yang sama sekali berbeda?",
    "Apa kelas favorit kamu di sekolah menengah?",
    "Apa pesta terbaik yang pernah kamu datangi?",
    "Apa hal paling bahagia yang pernah kamu rasakan?",
    "Apa hal paling cemas yang pernah kamu rasakan?",
    "Apa hal paling marah yang pernah kamu rasakan?",
    "Apakah kamu percaya pada Tuhan?",
    "Apa pertanyaan yang belum pernah kamu tanyakan kepada aku?",
    "Apa ciri kepribadian favorit kamu sendiri?",
    "Manakah dari ciri kepribadian kamu yang ingin kamu ubah?",
    "Pernahkah kamu benar-benar terobsesi dengan suatu topik?",
    "Apakah kamu mengumpulkan barang-barang sebagai seorang anak?",
    "Manakah dari orang tua kamu yang kamu datangi ketika kamu ingin berbicara?",
    "Apa hal paling menakutkan yang pernah kamu rasakan, sebagai seorang anak?",
    "Apa pencapaian yang paling kamu banggakan?",
    "Di mana kamu ingin tinggal dalam 10 tahun?",
    "Manakah dari teman kamu yang akan kamu pilih jika kamu harus berada di pulau terpencil hanya dengan satu orang?",
    "Siapa di antara teman kamu yang paling mirip dengan kamu?",
    "Apa pendapat kamu tentang pasangan yang sudah menikah tetapi tinggal di kota yang berbeda?",
    "Apa pendapat kamu tentang pasangan yang memiliki bisnis bersama dan menghabiskan seluruh waktu mereka bersama?",
    "Mana yang paling kamu sukai: rumah musim panas, liburan selama setahun, atau perahu?",
    "Apa yang akan kamu lakukan dengan satu juta dolar?",
    "Apa yang akan kamu lakukan dengan tambahan .000 untuk dibelanjakan hanya untuk diri sendiri?",
    "Ketika kamu masih kecil, apakah kamu merasa cocok?",
    "Apa pelajaran favorit kamu di sekolah menengah?",
    "Apakah kamu mengalami pubertas sebelum atau sesudah orang lain, atau tepat waktu?",
    "Siapa naksir pertamamu?",
    "Siapa ciuman pertamamu?",
    "Siapa orang pertama yang naksir kamu?",
    "Menurut kamu, apakah kamu seorang introvert atau ekstrovert?",
    "Jika kamu bisa kembali ke masa lalu, umur berapa kamu akan kembali?",
    "Jika kamu bisa melihat ke masa depan, apa yang ingin kamu ketahui?",
    "Apa bakat terbesar kamu?",
    "Apa sifatmu yang paling unik?",
    "Apa yang membuat aku berbeda dari orang lain yang pernah bersama kamu?",
    "Apa hal terbaik tentang hubungan kita?",
    "Apakah kamu pernah membandingkan diri kamu dengan cowok/cewek lain?",
    "Manakah dari teman aku yang menurut kamu paling menyenangkan?",
    "Apakah kamu seorang yang optimis, pesimis, atau seorang realis ?",
    "Ketika kamu bangun di tengah malam, apa yang kamu pikirkan?",
    "Jika kamu harus mengubah satu hal tentang diri kamu, apa yang akan kamu pilih?",
    "Menurut kamu, apakah aku lebih optimis, pesimis, atau realistis?",
    "Sebagai seorang remaja, apakah kamu pernah memberontak terhadap orang tua kamu?",
    "Siapa orang terdekat kamu di keluarga besar kamu?",
    "Apakah kamu pernah menginginkan lebih atau lebih sedikit saudara kandung?",
    "Bagaimana saudara kandung membentuk diri kamu?",
    "Apa malam kencan favorit kamu yang pernah kita alami?",
    "Apa pikiran rahasia kamu ketika kamu melihat aku di penghujung hari?",
    "Apakah kamu pernah berharap aku bisa membaca pikiran kamu? Kapan?",
    "Hal-hal apa tentang aku yang membuat kamu tahu bahwa aku adalah orang yang tepat untuk kamu?",
    "Jika Anda mengasosiasikan cinta dengan gambar, apakah itu?",
    "Menurut Anda, apa 3 bahan utama untuk membuat suatu hubungan berhasil?",
    "Apa saja ciri-ciri yang harus dimiliki oleh pasangan ideal Anda?",
    "Namun, apa saja karakteristik yang seharusnya tidak dimiliki oleh pasangan ideal Anda?",
    "Bagaimana Anda biasanya berperilaku selama perkelahian pasangan? Lalu?",
    "Apa hal pertama yang Anda lihat dalam diri seseorang?",
    "Apa hal pertama yang Anda perhatikan dalam diri saya?",
    "Kohabitasi atau pernikahan?",
    "Bagaimana Anda mengelola pembagian pekerjaan rumah tangga?",
    "Bagaimana Anda ingin merayakan pernikahan Anda?",
    "Berapa banyak hubungan yang Anda miliki sebelum saya?",
    "Bagaimana dan mengapa hubungan Anda sebelumnya berakhir?",
    "Apa hubungan Anda dengan mantan Anda?",
    "Apa nilai terbaik saya?",
    "Apa hal yang paling mengganggumu tentang aku?",
    "Apa yang Anda ingin saya menjadi lebih baik dan mengapa? Dan kau?",
    "Kapan Anda menyadari bahwa Anda ingin bersamaku?",
    "Apa yang harus saya lakukan untuk membuat Anda benar-benar bahagia?",
    "Jika Anda mengalami masa sulit, apa yang akan Anda lakukan untuk membuat saya merasa baik?",
    "Apa yang harus kita upayakan agar hubungan kita lebih baik?",
    "Jika Anda harus mempersembahkan sebuah lagu untuk diri saya sendiri, lagu apakah itu?",
    "Kegilaan terbesar apa yang pernah Anda lakukan untuk cinta?",
    "Dalam latar belakang keluarga apa Anda dibesarkan?",
    "Hubungan apa yang Anda miliki dengan orang tua Anda?",
    "Apa kenangan terbaik yang berhubungan dengan masa kecil Anda?",
    "Dan yang paling jelek?",
    "Anak macam apa kamu?",
    "Bagaimana Anda mirip dengan ibu Anda dan bagaimana dengan ayah Anda?",
    "Bagaimana Anda ingin berbeda dari orang tua Anda?",
    "Apa yang akan Anda lakukan secara berbeda jika Anda berada di posisi orang tua?",
    "Apakah Anda lebih suka tinggal dekat atau jauh dari orang tua Anda?",
    "Apakah Anda akan tinggal dekat dengan keluarga saya?",
    "Jika orang tua Anda tidak menyukai saya, apa yang akan Anda lakukan?",
    "Jika keluarga saya tidak sepenuhnya yakin dengan hubungan kami, apa yang akan Anda lakukan agar diterima?",
    "Apa kekecewaan terbesar yang telah Anda berikan kepada orang tua Anda dan yang telah mereka berikan kepada Anda?",
    "Bagaimana Anda mengatasi saat-saat sulit di masa lalu?",
    "Apakah Anda merasa cemburu jika saya melihat orang lain?",
    "Apakah Anda merasa terganggu jika saya berbicara dengan teman Anda?",
    "Apa yang akan Anda lakukan jika orang lain memukul saya?",
    "Jika saya bertanya, apakah Anda akan mengizinkan saya melihat ponsel Anda?",
    "Apa pendapat Anda tentang persahabatan antara pria dan wanita?",
    "Apakah Anda merasa terganggu jika saya berbicara tentang mantan pasangan saya?",
    "Apa yang akan Anda rasakan jika saya tetap berhubungan baik dengan mantan saya?",
    "Jika Anda memiliki kesempatan untuk berhubungan seks dengan orang lain, tanpa ketahuan, apakah Anda akan melakukannya?",
    "Jika Anda selingkuh, maukah Anda memberi tahu saya?",
    "Jika saya mengkhianati Anda, apakah Anda ingin tahu?",
    "Bisakah Anda memaafkan pengkhianatan?",
    "Jika saya meninggalkan Anda untuk orang lain, bagaimana reaksi Anda?",
    "Apa yang akan Anda lakukan agar pengkhianatan diampuni?",
    "Bagaimana Anda akan berperilaku jika saya memberi tahu Anda bahwa Anda tertarik pada orang lain, tanpa melakukan apa pun?",
    "Seberapa penting seks bagi Anda dalam suatu hubungan?",
    "Bagaimana hal itu membuat Anda mendengar tentang seks secara terbuka dengan pasangan Anda?",
    "Biasanya, seberapa sering Anda harus berhubungan seks dalam seminggu?",
    "Berapa lama Anda bisa bertahan tanpa berhubungan seks?",
    "Apa fantasi terbesarmu?",
    "Apa posisi favoritmu?",
    "Di mana Anda suka disentuh?",
    "Apa tempat teraneh yang pernah Anda lakukan berhubungan seks?",
    "Seberapa penting foreplay bagi Anda?",
    "Apa ingatan paling memalukan yang Anda miliki terkait dengan seks?",
    "Dengan siapa dan bagaimana pertama kali Anda? Berapa usia Anda?",
    "Hal apa yang paling membuat Anda bersemangat?",
    "Apa yang membuat keinginan Anda tiba-tiba mereda?",
    "Apakah Anda ingin bereksperimen dengan mainan seks di tempat tidur?",
    "Apakah Anda ingin memiliki anak di masa depan?",
    "Jika ya, berapa banyak anak yang Anda inginkan?",
    "Nilai-nilai apa yang ingin Anda sampaikan kepada anak-anak Anda?",
    "Jika Anda mandul dan menginginkan anak, bagaimana Anda akan bersikap?",
    "Apa yang ingin Anda ajarkan kepada anak-anak Anda?",
    "Bagaimana Anda mengatur pendidikan anak-anak Anda?",
    "Apa hal yang paling membuat Anda takut tentang memiliki anak?",
    "Menurut Anda, pada usia berapa menjadi orang tua adalah hal yang benar?",
    "Apa kesalahan besar yang menurut Anda bisa dilakukan oleh orang tua?",
    "Apa yang Anda tidak ingin anak Anda beri tahu?",

    "Bagaimana Anda memandang diri Anda sendiri, bekerja sebagai pembicara, antara sekarang dan 10 tahun?",
    "Seberapa penting pekerjaan dalam hidup Anda?",
    "Apakah Anda pernah mengorbankan keluarga Anda untuk bekerja?",
    "Apakah Anda lebih suka mendapatkan pekerjaan yang selalu Anda impikan atau temukan cinta sejati?",
    "Jika Anda pindah karena alasan pekerjaan, apakah Anda akan menerima hubungan jarak jauh?",
    "Apakah Anda akan berhenti dari pekerjaan Anda, untuk pindah ke tempat lain dengan pasangan Anda?",
    "Bagaimana perasaan Anda jika pasangan Anda berpenghasilan lebih dari Anda?",

    "Bagaimana Anda biasanya menghabiskan akhir pekan?",
    "Apa yang Anda suka lakukan di waktu luang?",
    "Apakah Anda seorang olahragawan? Jika ya, olahraga apa yang Anda sukai?",
    "Anda suka bepergian?",
    "Jika kita bisa berangkat besok, kemana kamu ingin pergi?",
    "Apakah Anda lebih suka makan di rumah atau di restoran?",
    "Apa liburan ideal Anda?c Kota seni atau laut?",
    "Apa hobimu",
    "Kegiatan apa yang akan Anda lakukan sebagai pasangan dengan saya?",
    "Jika saya meminta Anda untuk melakukan sesuatu dengan saya / untuk saya yang sangat membuat Anda bosan, apakah Anda akan menerimanya?",
    "Apa yang benar-benar tidak bisa Anda serahkan?",
    "Apakah Anda siap melakukan hal-hal baru atau Anda lebih suka rutinitas?",
    "Apa yang akan Anda bawa ke pulau terpencil?",
    "Film malam dan pizza atau disko?",
    "Apa kesalahan terbesarmu sejauh ini?",
    "Buku atau film apa yang Anda inginkan dapat Anda alami untuk pertama kali lagi?",
    "Apakah Anda malu dengan apa yang Anda lakukan di masa lalu? Jika Anda nyaman membicarakannya, apa itu?",
    "Menurut Anda, bias apa yang Anda miliki?",
    "Apakah Anda lebih suka tinggal di pedesaan, di kota, atau di kota besar? Mengapa?",
    "Apa yang normal sekarang yang akan dianggap tidak etis dan biadab dalam 100 tahun?",
    "Seberapa pemaaf Anda?",
    "Kapan Anda merasa benar-benar berada dalam elemen Anda?",
    "Teman apa yang sudah lama tidak terpikirkan oleh Anda?",
    "Apakah Anda percaya pada keberuntungan dan nasib buruk? Bagaimana dengan hal-hal yang beruntung atau tidak beruntung?",
    "Siapa orang paling menjengkelkan yang Anda kenal?",
    "Apa yang membawa arti bagi hidup Anda?",
    "Apa pujian terbaik yang Anda terima?",
    "Apa pelajaran hidup tersulit yang harus Anda pelajari?",
    "Pengalaman hidup apa yang Anda lewatkan?",
    "Apakah menurut Anda dunia membaik atau semakin buruk? Mengapa?",
    "Apa hal paling tidak etis yang Anda lakukan secara teratur?",
    "Apa kelemahan Anda?",
    "Apa kenangan terindah Anda tentang pohon?",
    "Seperti apa versi Anda yang terbaik?",
    "Apa yang paling Anda sukai ketika Anda memiliki waktu sendirian?",
    "Apa rahasia yang belum pernah Anda katakan kepada siapa pun?",
    "Apakah Anda mengambil 3 juta dolar jika itu berarti orang yang paling Anda benci di dunia mendapat 9 juta?",
    "Seberapa besar kemungkinan Anda percaya pada teori konspirasi?",
    "Kapan waktu favorit Anda?",
    "Apa 5 aturan utama Anda seumur hidup?",
    "Apa yang paling Anda nantikan hari ini?",
    "Apa dua peristiwa paling penting dalam hidup Anda?",
    "Apa hal yang paling berbahaya, mencari kesenangan yang akan Anda pertimbangkan lakukan?",
    "Jika Anda memiliki seorang teman yang berbicara kepada Anda dengan cara yang sama seperti Anda berbicara kepada diri sendiri, apakah Anda akan menjadikan mereka sebagai teman?",
    "Apakah Anda senang dengan jalur karier yang Anda pilih, atau apakah Anda berharap telah memilih karier yang berbeda?",
    "Apa tiga titik balik terpenting dalam hidup Anda?",
    "Apa penyesalan terbesarmu?",
    "Kapan kejadian atau peluang duniawi benar-benar mengubah jalan hidup Anda?",
    "Apa hadiah terbesar yang akan diterima?",
    "Apa hal tersedih dalam hidup Anda yang tak seorang pun tahu?",
    "Apa tidur yang paling damai / nyenyak yang pernah Anda alami?",
    "Menurut Anda seberapa baik Anda menangani penjara?",
    "Apa kesalahan terbaik Anda (bukan yang terburuk)?",
    "Jika Anda menerima gaji untuk mengikuti hasrat apa pun yang Anda inginkan, apa yang akan Anda lakukan?",
    "Apa perubahan paling signifikan yang ingin Anda lakukan dalam hidup Anda?",
    "Apa yang membuat Anda tidak menyukai seseorang?",
    "Seperti apa kehidupan sempurna Anda nantinya?",
    "Apakah Anda pikir Anda orang yang percaya diri? Mengapa atau mengapa tidak?",
    "Apa saja kisah yang diinduksi alkohol dari masa muda Anda?",
    "Apa saja tanda-tanda orang yang dangkal?",
    "Apa yang telah kamu perjuangkan dengan seluruh hidupmu?",
    "Apa sesuatu yang harus kita nikmati lebih banyak karena itu tidak akan ada lama?",
    "Seberapa tahayul Anda?",
    "Apa sesuatu yang Anda tahu buruk bagi Anda, tetapi Anda tidak bisa menghindarinya?",
    "Pertanyaan apa yang paling Anda inginkan jawabannya?",
    "Apa yang menjadi tema berulang dalam hidup Anda?",
    "Apa realisasi yang paling mengecewakan dan memilukan yang pernah Anda alami?",
    "Siapa yang kamu lakukan baik-baik saja tetapi diam-diam tidak suka?",
    "Hal sepele apa yang dilakukan orang membuat Anda gelisah?",
    "Apa hal paling ambisius yang Anda coba?",
    "Apa cara ideal Anda untuk menghabiskan liburan?",
    "Apa pelajaran tersulit yang harus Anda pelajari?",
    "Apa pengkhianatan terbesar yang pernah Anda alami?",
    "Apa hal terbaik dan terburuk tentang periode sejarah yang kita alami?",
    "Apa hal paling gila yang terjadi di pekerjaan tempat Anda bekerja?",
    "Apa periode paling sehat dan tidak sehat dalam hidup Anda?",
    "Alat musik apa yang Anda inginkan dapat Anda mainkan?",
    "Apakah ada kesalahan yang Anda lakukan selama bertahun-tahun, hanya untuk mengetahui kemudian bahwa Anda melakukan kesalahan?",
    "Siapa yang ingin kamu lebih sukai, atau siapa yang paling kamu kagumi?",
    "Apa kesalahan keuangan terbesar yang Anda buat?",
    "Ceritakan tentang saat kamu hampir mati?",
    "Apa yang kamu perjuangkan sehingga kamu tidak memberi tahu siapa pun?",
    "Apa hal favorit Anda di rumah Anda / kami?",
    "Apakah Anda senang dengan orang-orang di sekitar Anda? Mengapa atau mengapa tidak?",
    "Jika Anda dapat membuka bisnis, jenis bisnis apa yang akan Anda buka?",
    "Apa sesuatu yang Anda salah lakukan dan kemudian coba sembunyikan?",
    "Apa penderitaan emosi atau mental terburuk yang pernah Anda alami?",
    "Apa hal yang paling memuaskan dalam rutinitas harian Anda?",
    "Apakah Anda berharap tentang masa depan Anda?",
    "Apa yang membuat Anda kehilangan kepercayaan terhadap kemanusiaan ketika Anda memikirkannya?",
    "Apa sesuatu yang Anda takuti?",
    "Apa hal terburuk yang dibanggakan orang?",
    "Apa yang sengaja Anda abaikan meskipun Anda tahu Anda mungkin harus menghadapinya?",
    "Seberapa baik Anda membaca orang?",
    "Tiga kata apa yang paling menggambarkan Anda?",
    "Apa sesuatu yang ditakuti banyak orang, tetapi Anda tidak?",
    "Apa yang membuatmu merasa sangat mewah?",
    "Kapan Anda pergi ketika Anda ingin dikenang?",
    "Hal aneh apa yang membuatmu stres lebih dari yang seharusnya?",
    "Apa kentutmu yang paling tidak pantas atau memalukan?",
    "Menurutmu, kamu dilahirkan untuk pekerjaan apa?",
    "Apa saja kata-kata bijak yang telah melekat pada Anda selama ini?",
    "Apa yang telah menghabiskan terlalu banyak hidup Anda?",
    "Jika Anda dapat langsung mempelajari bakat atau keterampilan, apa yang ingin Anda ketahui bagaimana melakukannya?",
    "Apa yang ingin kamu lakukan dengan lebih baik?",
    "Apa saja hal-hal yang menurut Anda menjijikkan?",
    "Apa pertanyaan yang Anda ingin orang lebih sering tanyakan?",
    "Apa yang ingin Anda katakan kepada orang tetapi tidak bisa?",
    "Apa hal yang paling menyakitkan untuk didengar?",
    "Apa yang paling Anda sukai dari tempat tinggal kita?",
    "Kemewahan seperti apa yang Anda nikmati?",
    "Jika uang bukan masalah, dan tanpa masukan dari saya, bagaimana Anda akan menghias rumah Anda / kami?",
    "Apa kebaikan terbesar yang telah Anda lakukan untuk seseorang?",
    "Seberapa baik Anda mengenal diri sendiri?",
    "Hewan apa yang paling kamu takuti?",
    "Apa situasi paling menegangkan yang pernah Anda alami? Bagaimana Anda menanganinya?",
    "Apa cara terbaik bagi seseorang untuk meningkatkan diri?",
    "Menurut Anda apa yang terjadi setelah kematian?",
    "Apa yang jauh lebih sulit daripada kedengarannya?",
    "Jika Anda memiliki satu juta dolar untuk diberikan kepada amal apa pun, jenis amal apa yang akan Anda berikan?",
    "Kapan terakhir kali Anda menangis?",
    "Jika Anda dapat melakukan perjalanan ke negara mana saja di dunia selama satu bulan, ke mana Anda akan pergi?",
    "Siapa yang paling Anda lewatkan?",
    "Apa tempat paling menakutkan / paling menakutkan yang pernah Anda kunjungi?",
    "Apa saja sifat paling menarik yang dapat dimiliki seseorang?",
    "Apa yang membuatmu takut setiap hari?",
    "Hal tidak benar apa yang Anda yakini untuk waktu yang sangat lama?",
    "Jika ada kecelakaan mengerikan dan Anda tidak sadarkan diri dan pada dukungan hidup, berapa lama Anda ingin menjadi pendukung kehidupan?",
    "Apa kisah Anda yang paling memalukan tentang sakit?",
    "Apa yang Anda inginkan dari kehidupan?",
    "Apa yang paling membuatmu bersukacita?",
    "Bagaimana rutinitas pagi Anda saat ini dibandingkan dengan rutinitas pagi ideal Anda?",
    "Bagaimana menurut Anda masyarakat berubah? Apakah Anda pikir kami akan berubah dengannya?",
    "Seberapa sering Anda mengubah pendapat Anda atau bagaimana Anda memandang dunia?",
    "Apa yang dapat dilakukan seseorang yang membuat mereka langsung tidak menarik bagi Anda, betapapun menariknya mereka secara fisik?",
    "Apa saja sensasi yang paling menyenangkan bagi Anda?",
    "Apa waktu paling produktif dalam hidup Anda? Bagaimana dengan yang paling tidak produktif?",
    "Bagaimana dengan dirimu sendiri, apa yang paling kamu banggakan?",
    "Apa yang kamu khawatirkan?",
    "Apakah menurut Anda lebih banyak orang yang memandang rendah Anda atau Anda? Mengapa?",
    "Bagian mana dari Anda sebagai pribadi yang masih membutuhkan banyak pekerjaan?",
    "Skandal apa yang terjadi di tetangga atau kota Anda ketika Anda tumbuh dewasa?",
    "Apa yang Anda anggap remeh?",
    "Menurut Anda apa sifat kepribadian terbaik dan terburuk Anda?",
    "Apa peluang terbesar yang Anda terima?",
    "Apa yang ingin Anda sampaikan dari obituari Anda?",
    "Bagaimana kamu jatuh dengan beberapa teman dekat kamu sebelumnya?",
    "Seberapa baik Anda berfungsi di bawah banyak tekanan?",
    "Kapan kamu yang paling “kamu”?",
    "Apa yang paling menenangkan Anda?",
    "Apa situasi sosial paling canggung yang pernah Anda alami?",
    "Apakah lebih baik mempercayai orang atau tidak mempercayai orang? Dan mengapa?",
    "Apa ingatan favorit Anda tentang seseorang yang tidak ada dalam hidup Anda lagi?",
    "Kesenangan kecil apa yang paling Anda nikmati?",
    "Berapa umur yang ingin Anda jalani?",
    "Apa yang paling sentimental tentang Anda?",
    "Bagaimana Anda membayangkan hari-hari kita setelah kita pensiun?",
    "Jika saya sakit, bagaimana Anda akan merawat saya?",
    "Bagaimana Anda membayangkan seks setelah usia tertentu?",
    "Jika Anda punya pilihan, di mana Anda lebih suka menghabiskan masa tua?",
    "Menurut kamu, apa rahasia agar tidak cepat lelah setelah hidup bersama?",
    "acara TV apa yang paling tidak kamu sukai dan Beri tahu alasannya!",
    "kapan terakhir kali kamu berbohong? Dan apa kebohongan tersebut!",
    "kapan terakhir kali kamu menangis? Dan apa yang menjadi penyebabnya",
    "kapan terakhir kali kamu kentut?",
    "apa ketakutan terbesar yang kamu miliki?",
    "apa fantasi terbesar atau teraneh yang kamu miliki?",
    "apa hal yang membuatmu merasa senang namun orang tuamu tidak mengetahuinya?",
    "pernahkah kamu diselingkuhi? Kapan dan oleh mantan yang keberapa?",
    "hal terburuk apa yang pernah kamu lakukan? Apakah berdampak ke orang lain?",
    "apa rahasia yang belum pernah kamu ceritakan kepada siapapun?",
    "apakah kamu memiliki bakat terpendam? Apa Itu?",
    "siapa selebriti yang pertama membuatmu jatuh cinta?",
    "apa pendapatmu mengenai perselingkuhan yang dilakukan seseorang?",
    "apa pengalaman intim terburuk yang pernah kamu alami?",
    "apakah kamu pernah melanggar hukum? Kemudian hukum seperti apa yang kamu langgar?",
    "hal apa yang paling memalukan yang pernah kamu lakukan? Serta kapan kamu melakukannya?",
    "hal apa yang paling membuatmu merasa insecure? Dan mengapa demikian?",
    "apa Kesalahan terburuk yang pernah kamu lakukan?",
    "hal paling menjijikkan apa yang pernah kamu lakukan?",
    "siapa orang yang paling ingin kamu cium di antara kita?",
    "hal terburuk apa yang pernah dilakukan orang lain kepadamu?",
    "apa kebiasaan terburukmu? Sebutkan tiga diantaranya",
    "apa penyesalan terburuk yang kamu miliki?",
    "kenapa kamu putus dengan mantanmu yang sebelumnya? Jabarkan alasannya",
    "jika kamu bisa menjadi tidak terlihat, hal pertama apa yang akan kamu lakukan?",
    "apa rahasia yang kamu sembunyikan dari orang tuamu?",
    "hadiah termurah yang pernah kamu berikan untuk orang lain? Dan kepada siapa kado itu diberikan?",
    "hal tergila apa yang pernah kamu lakukan untuk bisa bebas dari tilang polisi?",
    "hal terkejam apa yang pernah kamu lakukan atau katakan kepada pasanganmu?",
    "hal terkejam apa yang pernah kamu ungkapkan kepada orang lain?",
    "hal terkejam apa yang pernah kamu katakan tentang orang lain?",
    "apa hal paling kekanak-kanakan yang masih kamu lakukan hingga saat ini?",
    "apa Hal paling memalukan yang pernah kamu posting di media sosial?",
    "apa Hal paling menakutkan yang pernah kamu lakukan?",
    "apa Hal paling menakutkan yang pernah terjadi padamu?",
    "apa Hal paling menjijikkan yang pernah kamu lakukan sendirian?",
    "hal terakhir yang kamu cari di Google? Tunjukan!",
    "hal teraneh apa yang pernah kamu lakukan saat mengemudi?",
    "siapa orang yang diam-diam sedang kamu sukai?",
    "siapa orang terakhir yang sedang kamu kepoin di media sosial?",
    "apa tontonan favorit saat masih kecil? Sebutkan tiga diantaranya",
    "siapa orang yang paling sering kamu chat? Sebut orangnya",
    "apa kebohongan terbesar yang pernah kamu ucapkan kepada kedua orang tuamu?",
    "apa mimpi teraneh yang pernah kamu alami? ceritakan",
    "ceritakan detail ciuman pertamamu…",
    "kapan terakhir kali kamu ngompol?",
    "menurutmu, hewan apa yang terlihat paling mirip denganmu? Sebutkan tiga!",
    "di antara semua orang di ruangan ini siapa yang paling kamu suka dalam konteks romantis?",
    "siapa mantan terindahmu? Sebutkan namanya",
    "siapa orang yang ingin kamu jadikan istri atau suami?",
    "apakah kamu pernah melakukan ghosting kepada seseorang?",
    "apa ada aib yang kamu sembunyikan dari kami?",
    "berapa jumlah mantanmu? Sebutkan semua namanya",
    "siapa nih crush rahasia kamu?",
    "punya berapa crush selama hidup? Sebut namanya",
    "tiga hal apa yang harus gebetan atau pacarmu punya? Apa saja itu, sebutkan!",
    "di antara pemain, siapa yang paling dekat atau paling tahu banyak tentangmu?",
    "first impression tentang (nama orang)?",
    "Baca atau buatlah puisi dengan tema (alam/cinta/sesuatu yang absurd) selama kurun waktu dua menit kemudian bacakan.Berikan akun Instagrammu ke (nama orang) selama 30 menit",
    "Izinkan (nama orang) untuk mengatur gaya rambutmu",
    "Izinkan (nama orang) untuk mengatur ulang make-up di wajahmu",
    "Kamu harus menuruti semua perkataan (nama orang) dalam kurun waktu 20 menit ke depan",
    "Ulangi apa yang dikatakan orang yang ada di sampingmu hingga kamu mendapat giliran lagi",
    "Keluarkan semua isi tas, kantiong, dompet, dan semua bawaan",
    "Panggill orang yang dipilih sama (nama orang) kemudian nyanyikan lagu Happy Birthday tapi dibalik",
    "Panggil orang yang sudah taken kemudian katakan bahwa kamu tertarik kepada pasangannya",
    "Publish karya apapun yang pernah kamu buat langsung saat itu juga ke halaman InstaStory",
    "Tirulah gaya YouTuber atau TikTok hingga akhirnya bisa ditebak oleh orang lain",
    "Cobalah salah satu tren TikTok ataupun dance TikTok serta upload ke InstaStory",
    "Buat tato dengan menggunakan spidol permanen di area tubuh yang terlihat",
    "Tunjukkan liked videos di TikTok ataupun post yang disukai di Instagram",
    "Tunjukkan juga daftar chat terakhir di WhatsApp atau LINE",
    "Tunjukkan history dari browser ponsel atau laptop dan smartphone mu",
    "Tunjukkan history pencarian pada halaman Instagram atau TikTok atau LINE",
    "Tunjukkan foto-foto maupun video terbaru di galeri handphone mu",
    "Push-up lah sebanyak satu kali setiap ada orang yang bilang “aku” selama 10 menit ke depan",
    "Makanlah sayur-sayuran mentah pertama yang terlihat di kulkas",
    "Checkoutkan satu barang dengan budget maksimal (di suatu nominal tertentu) dari keranjang Shopee atau Tokopedia (nama orang)",
    "GoFood/GrabFoodlah apapun yang (nama orang) mau",
    "Beli subscription baik itu Netflix ataupun Spotify untuk nama orang",
    "Kirim e-money (baik itu OVO/GoPay/Dana) kepada orang di ruangan, dan pilih secara random",
    "Makanlah satu gigitan kulit pisang",
    "Katakan ‘meong’ pada setiap akhir kalimat hingga tiba di giliranmu yang selanjutnya",
    "Tirukan seorang selebriti hingga ada yang dapat menebak siapa seleb yang kamu tirukan",
    "Bertingkahlah seperti ayam hingga giliranmu yang selanjutnya",
    "Biarkan salah satu orang menggambar tato di wajahmu",
    "Gunakan penutup mata kemudian raba wajah salah satu di antara kalian hingga kamu dapat menebak siapa orang itu",
    "Segera ungkapkan perasaanmu kepada gebetan",
    "Lakukan gerakan push up sebanyak 20 kali",
    "Lakukan gerakan kayang selama kurang lebih satu menit",
    "Lakukan Gerakan Plank selama kurang lebih satu menit",
    "Biarkan salah satu di antara kalian saling merias wajah dengan menggunakan make up",
    "Bacalah dengan lantang pesan-pesan terakhir kali kamu kirim ke gebetan",
    "Telepon seorang teman kemudian katakan kepadanya selamat ulang tahun sambil menyanyikan lagu ulang tahun",
    "Ayo bangun dan tunjukkan gerakan dance terbaikmu, unggah di instagram",
    "Ulangi setiap perkataan orang yang ada di sampingmu hingga sampai kepada giliranmu yang selanjutnya",
    "Telepon orang yang ada di kontak HP secara random kemudian nyanyikan lagu terakhir yang sedang kamu dengarkan",
    "Pesan makanan secara online kemudian buat pesanan ini diberikan kepada sopir yang menerima pesanan yang telah kamu bayar",
    "Buatlah story dengan menggunakan filter yang paling tidak kamu sukai di halaman Instagram",
    "Rekam suaramu saat kamu sedang bernyanyi lagu kesukaan kemudian unggah di Instagram tanpa di edit secara langsung",
    "Buat salah satu TikTok challenge yang sedang viral dan unggah secara langsung",
    "Unggahlah salah satu foto yang paling kamu sukai dari gebetan",
    "Teleponlah orangtua kemudian sampaikan kepadanya bahwa kamu merindukannya",
    "Kirimlah pesan secara random kepada salah satu followers akun Instagram yang dipilih secara random juga sebelumnya",
    "Bernyanyilah RAP selama tiga menit tanpa ada jeda",
  ],
  english: [
    "a secret you kept from your parents 👀",
    "ain't no way",
    "any pets?",
    "are you a back seat driver?",
    "are you close with your parents?",
    "are you gonna get a tat",
    "are you judgemental",
    "are you looking to date someone rn",
    "are you straight?",
    "are you talking to anyone?",
    "Biggest red flags for a girl?",
    "biggest red flags in a guy?",
    "biggest regret?",
    "body count 😳?",
    "can we be besties",
    "craziest pickup line that worked?",
    "did you have an imaginary friend?",
    "did you watch game of thrones?",
    "do u have a dog?",
    "do u use pronouns",
    "do you even like school?",
    "do you have a middle name?",
    "do you have any cute friends for me lmao",
    "do you have any piercings?",
    "do you have trust issues?",
    "do you love ur life? x",
    "do you snore?",
    "do you speak another language?",
    "do you want kids evenutally?",
    "dogs or cats?",
    "dont leave me on opened",
    "dream job?",
    "ever gone skinny dipping?",
    "everything ok?",
    "favorite food?",
    "favorite movie?",
    "Favorite movie/ tv series rn",
    "favorite show rn?",
    "have any netflix recomendations??",
    "have any netlix recomendations?",
    "have u seen breaking bad",
    "have you done drugs 🍃",
    "Have you ever been fired from a job?",
    "have you ever cheated, you gotta be honest lol",
    "have you ever cried during a movie 🤷",
    "have you ever given a hickey?",
    "have you ever gotten in a fist fight?",
    "have you ever had any surgery",
    "have you ever thought about being bi",
    "have you ever watched harry potter?",
    "hottest sport? 🥵",
    "how are you feeling today :)",
    "How are you today ❤️‍🩹",
    "how big of nerd are you 1 to 10",
    "how many exes do you have?",
    "how many hours of sleep you get last night?",
    "how many kids do you want to have",
    "how many selfies do you take a day?",
    "how many stuffed animals you own?",
    "how old are you again?",
    "how old do u wanna be whe u get married?",
    "how tall are u",
    "how tall are you??",
    "how tall r u",
    "How's you day going ??!",
    "I have a crush on you",
    "I have covid, any show recomendations?",
    "I know what you did",
    "i love uuuuuu!!",
    "i miss you",
    "i really like you",
    "insta?",
    "introvert or extrovert?",
    "is it true???",
    "is ngl the best app tho :)",
    "kanye is the best 😤 change my mind",
    "name all your exes",
    "netflix and chill? 👀",
    "not gonna judge but why...",
    "one friend ur thankful for...",
    "one thing you can't survive without?",
    "opinion on birds?",
    "personality or looks?",
    "please give me pickup lines that always work",
    "should i be honest with you on here?",
    "shout me out",
    "single?",
    "spill some tea",
    "spill the tea on your first kiss.",
    "tell me a funny joke",
    "tell me a random fact",
    "the longest time you've ever gone without showering?",
    "the most embarrassing thing you've ever done?",
    "the weirdest place you've ever gone to the bathroom?",
    "the weirdest thing you've ever eaten?",
    "The weirdest trend you've done",
    "the worst advice you've ever given?",
    "the worst date you've ever been on?",
    "the worst food you ever eaten?",
    "the worst pick up line you've ever heard?",
    "the worst trouble you go into as a kid?",
    "u busy this weekend?",
    "uh what did you eat for breakfast?",
    "we should talk more",
    "what are ur plans this weekend?",
    "what are you wearing?",
    "what color is your room?",
    "what did you dream about last night?",
    "what have you gotten detention for?",
    "What is your shoe size?",
    "what music do you listen to",
    "what phone do you have?",
    "what time did you fall asleep last night?",
    "what time do you usually go to bed?",
    "what was the best day so far this year?",
    "what was ur worst day ever",
    "what was your favorite show when you were a kid?",
    "What's ur fav brand?? <3",
    "whats in ur spotify top songs",
    "whats the last thing you ate?",
    "whats the stupidest thing you thought as a kid?",
    "whats ur fav book",
    "whats ur fav drink",
    "whats ur fav food",
    "whats ur fav movie",
    "whats ur fav song",
    "whats ur fav tv show",
    "whats ur favorite food?",
    "whats ur oritenation",
    "whats your biggest insecurity 🤔",
    "whats your dream house",
    "whats your fav sport?",
    "whats your number one song on spotify",
    "whats your sign",
    "when was the last time you cried?",
    "when was the last time you lied?",
    "when was the last time you wet the bed?",
    "when was your first kiss?",
    "where are you from...?",
    "where are your parents from?",
    "who are your best girl friends",
    "who do you have pinned on imessage",
    "who do you miss the most",
    "who do you text the most?",
    "who was the last dude you texted?",
    "who was the last girl you texted?",
    "who was your crush in middle school lmao",
    "who was your first kiss?",
    "who you tryna get with 👀",
    "who you tryna vote for in 2024 👀",
    "whos the last person you texted?",
    "whos ur best friend",
    "whos ur crush?",
    "whos ur worst enemy 😈",
    "whos your last ig search?",
    "whos your last snap from?",
    "why doesnt my crush like me back 😭",
    "worst movie youve ever watched?",
    "would you ever be fwb",
    "would you ever get with me? ~ N",
    "would you leave your SO for a celeb",
    "would you say yes if i asked you out - A",
    "wyd",
    "wyd tomorrow",
    "yo stop leaving me on read",
    "you a homie",
    "you ever think about having the ability to teleport?",
    "you got a sneaky link?",
    "you have good style",
    "you lit",
    "you should get a tattoo",
    "you should post more selfies 💕",
    "you wild for what you did",
    "you're best friend",
    "Your biggest fear?",
    "your biggest insecurity?",
    "your celeb crush?",
    "your favorite hobby?",
    "your favorite part of your body?",
    "your last song on your spotify?",
    "your really attractive",
    "your worst habit?",
    "your worst personality characteristic?",
    "youre cute",
  ],
};

const questionsId = questions.indonesian;

var chars =
  "0123456789abcdefghijklmnopqrstuvwxyz!@#$%^&*()ABCDEFGHIJKLMNOPQRSTUVWXYZ";
let spammerStatus = "idle";
const log = {
  usernames: {},
  sent: [],
};

const targets = [];

const sendQuestion = async (username, randomQuestion, deviceId) => {

};

const generateId = () => {
  let randomId = "";
  for (var i = 0; i <= 20; i++) {
    var randomNumber = Math.floor(Math.random() * chars.length);
    randomId += chars.substring(randomNumber, randomNumber + 1);
  }
  return randomId;
};

const sleep = async (sleepfor) => {
  return await new Promise((r) => setTimeout(r, sleepfor));
};

const sendQuestionToUser = async (username) => {
  let randomQuestion =
    questionsId[Math.floor(Math.random() * questionsId.length)];
  let randomId = generateId();
  const res = await sendQuestion(username, randomQuestion, randomId);
  if (res.status >= 400) {
    const sleepfor = 60 * 1000;
    console.log("error " + res.status + " " + res.statusText);
    console.log(`sleeping for ${sleepfor / 1000} seconds\n`);

    await sleep(sleepfor);
    return false;
  }
  const count = log.usernames[username] || 0;
  console.log(`(#${count}) Sent(@${username}): ${randomQuestion}`);
  // get date time now
  const now = new Date();
  const date = now.getDate();
  const month = now.getMonth() + 1;
  const year = now.getFullYear();
  const hour = now.getHours();
  const minute = now.getMinutes();
  const second = now.getSeconds();
  const dateTime = `${date}/${month}/${year} ${hour}:${minute}:${second}`;
  log.sent.push({
    username: username,
    text: randomQuestion,
    dateTime: dateTime,
  });

  if (log.usernames[username]) {
    log.usernames[username] = count + 1;
    return { username: username, text: randomQuestion };
  }
  log.usernames[username] = 1;
  return { username: username, text: randomQuestion };
};

const addTarget = (target) => {
  if (target === "") return;
  const index = targets.findIndex((t) => t.username === target);
  if (index !== -1) return;
  targets.push({ username: target, active: true });
  log[target] = 0;
  postMessage({ type: "log", targets: targets, log: log });
};

const deleteTarget = (target) => {
  if (target === "") return;
  const index = targets.findIndex((t) => t.username === target);
  if (index === -1) return;
  targets.splice(index, 1);
  postMessage({ type: "log", targets: targets, log: log });
};

const toggleTarget = (target) => {
  if (target === "") return;
  const index = targets.findIndex((t) => t.username === target);
  if (index === -1) return;
  targets[index].active = !targets[index].active;
  postMessage({ type: "log", targets: targets, log: log });
};

const messageLog = (target) => {
  // filter only the target
  const filteredLog = log.sent.filter((l) => l.username === target);
  postMessage({ type: "messageLog", log: filteredLog });
};

onmessage = async (e) => {
  switch (e.data.type) {
    case "start":
      spammerStatus = "active";
      break;
    case "stop":
      spammerStatus = "idle";
      break;
    case "add":
      addTarget(e.data.target);
      break;
    case "delete":
      deleteTarget(e.data.target);
      break;
    case "toggle":
      toggleTarget(e.data.target);
      break;
    case "messageLog":
      messageLog(e.data.target);
    default:
      break;
  }
};

const getActiveTargets = async () => {
  return targets.filter((t) => t.active);
};

async function starSpamming() {
  while (true) {
    if (spammerStatus === "idle") {
      console.log("spammer is idle");
      await sleep(2000);
      continue;
    }
    const activeTargets = await getActiveTargets();
    if (targets.length === 0 || activeTargets.length === 0) {
      console.log("no targets");
      await sleep(2000);
      continue;
    }
    // pick one of targets randomly
    const randomTarget = targets[Math.floor(Math.random() * targets.length)];
    if (!randomTarget.active) continue;
    const res = await sendQuestionToUser(randomTarget.username);
    if (res)
      postMessage({
        type: "log",
        targets: targets,
        log: log.usernames,
      });
    await sleep(1000);
  }
}

starSpamming();
